/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdad6",
        "on-tertiary-container": "#f7fff1",
        "on-secondary-fixed": "#001c3a",
        "inverse-surface": "#2e3132",
        "primary-container": "#db322f",
        "on-tertiary-fixed": "#002204",
        "tertiary-fixed-dim": "#7ddc7a",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#5b403d",
        "surface": "#f8f9fa",
        "inverse-primary": "#ffb4ac",
        "surface-dim": "#d9dadb",
        "background": "#f8f9fa",
        "secondary-fixed": "#d4e3ff",
        "primary": "#b7131a",
        "tertiary-container": "#268630",
        "surface-bright": "#f8f9fa",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#004786",
        "tertiary": "#006b1b",
        "on-tertiary-fixed-variant": "#005313",
        "secondary-container": "#54a0fe",
        "surface-tint": "#bb171c",
        "surface-container-high": "#e7e8e9",
        "surface-container-low": "#f3f4f5",
        "on-primary-fixed": "#410002",
        "on-secondary-container": "#003567",
        "surface-container-highest": "#e1e3e4",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#93000d",
        "secondary": "#005faf",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#a5c8ff",
        "outline-variant": "#e4beb9",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fffbff",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#ffb4ac",
        "tertiary-fixed": "#98f994",
        "surface-container": "#edeeef",
        "inverse-on-surface": "#f0f1f2",
        "outline": "#906f6c",
        "surface-variant": "#e1e3e4",
        "on-background": "#191c1d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "16px",
        "xl": "24px",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "xl": "32px",
        "container-max": "1280px",
        "md": "16px",
        "gutter": "24px",
        "xxl": "48px",
        "xs": "4px",
        "base": "8px",
        "lg": "24px"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "label-lg": ["Inter"],
        "title-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "display-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0.5px", "fontWeight": "400"}],
        "label-sm": ["11px", {"lineHeight": "16px", "letterSpacing": "0.5px", "fontWeight": "500"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1px", "fontWeight": "500"}],
        "title-lg": ["22px", {"lineHeight": "28px", "fontWeight": "500"}],
        "headline-md": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.25px", "fontWeight": "400"}],
        "display-lg": ["57px", {"lineHeight": "64px", "letterSpacing": "-0.25px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
